name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build pkg-config \
            libasound2-dev libx11-dev libxrandr-dev libxinerama-dev \
            libxext-dev libxi-dev libxcursor-dev libfreetype6-dev \
            libgl1-mesa-dev libglu1-mesa-dev libgtk-3-dev

      - name: Configure (CMake + Ninja)
        run: |
          cmake -S SeratoLikeSampler -B build -G Ninja \
            -D CMAKE_BUILD_TYPE=Release \
            -D JUCE_FETCH_VST3_SDK=ON

      - name: Build
        run: cmake --build build --config Release --parallel

